### ISSUE TITLE
Transport quantities

### ISSUE THREAD

**Issue by juanrallg** [sonofeft/RocketCEA#13]
I have noticed an inconsistency in the tranport variables (viscosity, conductivity, and thus Pr number) between the rocketcea output and the "vanilla" cea2. We have done a double check with a 2004 cea version and the cearun online. These two versions provide identical results, with rocketcea returning different values for the mentioned quantities (the rest, T,P,rho, etc are identical in all three).
The inconsistency can be seen in the full cea output generated by rocketcea as well (f.out file). This might indicate the problem is in the py_cea.f implementation, but we haven't been able to identify the issue.

**Comment by sonofeft** [comment]
When comparing cases, make sure that the propellants are being run with the same heat of formation. RocketCEA uses values that may differ slightly from the values that NASA uses (see: RocketCEA propellants LCH4_NASA, LH2_NASA, LO2_NASA).  

The heat of formation shows up in the output, check the lines:

```
             REACTANT                    WT FRACTION      ENERGY      TEMP
                                          (SEE NOTE)      CAL/MOL       K  
 FUEL        H2(L)                        1.0000000     -2154.000     20.270
 OXIDANT     O2(L)                        1.0000000     -3102.000     90.180

```
To run a RocketCEA case with a different Hf, see: `https://rocketcea.readthedocs.io/en/latest/new_propellants.html`

If that fails to explain the difference, compare the files trans.inp and thermo.inp that CEA uses to drive those calculations.
Since the FORTRAN code in RocketCEA for transport properties is identical to the 2004 CEA code I suspect input differences.

If you still have problems, send me input and output files that display the problem so I can recreate and diagnose them.
