### ISSUE TITLE
CEA Returning Zero Values in Example

### ISSUE THREAD

**Issue by aVeryLargeBird** [sonofeft/RocketCEA#18]
CEA is returning zero whenever I call a function. For example: 

```
from rocketcea.cea_obj import CEA_Obj
C = CEA_Obj( oxName='LOX', fuelName='LH2')
for mr in range(2,9):
    print(mr, C.get_Isp(Pc=100.0, MR=mr, eps=40.0) )
```

has been returning me: 
2 0.0
3 0.0
4 0.0
5 0.0
6 0.0
7 0.0
8 0.0

Can anyone help? Thank you

**Comment by sonofeft** [comment]
I would guess an installation problem. What system are you on? What output do you see when you install RocketCEA? Did the quick test at https://rocketcea.readthedocs.io/en/latest/quickstart.html#install-rocketcea work?

**Comment by sonofeft** [comment]
I have no experience with Anaconda, however the following approach worked for another user with Anaconda and 64 bit python 3.9.

Download "mingw-w64-install.exe" from:
https://sourceforge.net/projects/mingw-w64/

Install MinGW using instructions at:
https://rocketcea.readthedocs.io/en/latest/installgfortran.html#windows-10

Install RockeCEA using instructions at:
https://rocketcea.readthedocs.io/en/latest/quickstart.html#windows-batch-file

This approach was tested on a clean Windows 10 installation and it worked with 64 bit python 3.9
and will hopefully work on your python 3.8

**Comment by JFGrobusch** [comment]
I ran into the same issue. Running `python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='LOX', fuelName='LH2'); print(C.get_Isp())"` returns 0.0. I initially also installed python with Anaconda, but the issue persists with a clean install of python 3.9.6. 

There is a single error during the installation process (image), occuring after setup.py is run (image attached). Could this be causing the issue?

**Comment by JFGrobusch** [comment]
Turns out the error i was getting above was not the issue. It was related to the installation filepath constaining a space, which I fixed. So now im completely at a loss, unfortunately, as I encounter zero errors during installation but the issue persists.

**Comment by sonofeft** [comment]
I set up a clean install of Anaconda on a Windows 10 virtual machine and followed the instructions at: https://rocketcea.readthedocs.io/en/latest/quickstart.html#anaconda-windows-batch-file

It installed correctly for me. 
I will close this issue, however, if you are still having trouble, feel free to reopen it.

**Comment by RasmusAPedersen** [comment]
I am seeing a similar error. I don't have a fresh Windows 10 install, but I have a fresh Anaconda3 install.

I ran the commands in the Anaconda batch file one by one, and I ended up with a return on the final check of "0.0"

I did some snooping and found out that RocketCEA uses my personal user folder to save intermediate .inp and .out files. I checked these, and I noticed that they would never change regardless of if I ran the .getISP with other parameters. Not really sure how to troubleshoot this. @sonofeft can you help?

**Comment by sonofeft** [comment]
I have very little experience with Anaconda. My Jan 11 setup seemed to work with little difficulty.
I know from past experience, that any spaces in path names will likely cause problems with RockeCEA.

Please read the NARRATIVE and then the ADVICE.

------------ NARRATIVE ------------

RocketCEA uses a modified NASA CEA FORTRAN code named "py_cea.f".

When running cases, py_cea.f builds an internal in-memory input file; it does not use an input file on the systems hard drive.

Normally, when RocketCEA is run, no output file is created. After the FORTRAN DLL library is executed, the COMMON BLOCK memory locations are read directly (NOTE: this provides more numerical precision than the standard formatted output text file.). 

If a CEA output file is desired, the parameter "makeOutput = 1" should be set when instantiating the CEA_Obj.
(The file "f.out" will be created in the user directory, see below)

Many years ago, when I was modifying the NASA cea2.f code, I had trouble making it work unless CEA could verify the existence of "dummy" input and output disk files (Even though they are typically not used).

Back in the python 2.x days, those files were incuded in the package install directory (e.g. "python2.x\Lib\site-packages\...\rocketcea") as "f.inp" and "f.out".

More recent versions of RocketCEAmore recent versions of RocketCEA, in order to overcome Windows and python permissions, had to move the "dummy" input and output files from the rocketcea folder in "...\Lib\site-packages\...\rocketcea" to the user's home directory. 

The code below shows how the user's home directory and data directory for f.inp and f.out are determined.

USER_HOME_DIR = os.path.dirname( os.path.expanduser('~/') )
ROCKETCEA_DATA_DIR = os.path.join( USER_HOME_DIR, 'RocketCEA' )

NOTE: any spaces in ROCKETCEA_DATA_DIR will likely be a problem.

There is also a debug flag that can be set when instantiating CEA_Obj (see code snippet below).

That debug flag was mainly for me during my "dark-age" development years, however, it is possible that it may reveal some issues in this instance.

One final observation is that RocketCEA initializes many of the COMMON BLOCK variables to 0.0 prior to each run.

Getting 0.0 as an output, probably means that the FORTRAN code returned on an error condition.

------------ ADVICE ------------

Run the following code with makeOutput=1, make_debug_prints=True

<<< code snippet >>>
from rocketcea.cea_obj import CEA_Obj, ROCKETCEA_DATA_DIR
print( ROCKETCEA_DATA_DIR )
C = CEA_Obj( oxName='LOX', fuelName='LH2', makeOutput=1, make_debug_prints=True)
Isp = C.get_Isp(Pc=100.0, MR=1.0, eps=40.0)
print( Isp )
<<< end of code snippet >>>

A working install will print:
<ROCKETCEA_DATA_DIR>  (for example:   C:\Users\Charlie\RocketCEA )
NOTICE... making an output file
374.30361765576265

Look for spaces in the <ROCKETCEA_DATA_DIR> name.

Will create "f.out" in the ROCKETCEA_DATA_DIR subdirectory.
Look for any issues that CEA may have raised inside the "f.out" file.

It is possible that some debug information will be printed by python, outside of the FORTRAN code, that may help.


------------ MORE ADVICE ------------

Run the same code snippet from above, however, this time edit the RocketCEA code "cea_obj.py" at about line 37.
Change the line:   USER_HOME_DIR = os.path.dirname( os.path.expanduser('~/') )
To something like: USER_HOME_DIR = "C:\\temp"  # or any other path w/o spaces.

Please let me know if any of this helps.

**Comment by RasmusAPedersen** [comment]
That was incredible. I spent the whole day yesterday trying to figure it out, and the issue was that I indeed had whitespaces in my Windows user home directory. I manually input a new USER_HOME_DIR in the cea_obj.py file to the root of another drive ('D:\\' in my case), and it instantly worked.

Thanks a lot for your help and for RocketCEA in general!

**Comment by sonofeft** [comment]
Today (4/12/2022), I uploaded RocketCEA version 1.1.28

On Windows, version 1.1.28 will check for spaces in the RocketCEA working directory and try to fix the issue automatically by using Windows 8.3, short name format for the path.
    
If the above approach fails, a new function (set_rocketcea_data_dir) has been added to allow the user to specify a working directory of their choice.

for example:
    
from rocketcea.cea_obj import CEA_Obj, set_rocketcea_data_dir
set_rocketcea_data_dir( r'D:\temp\RocketCEA' )

C = CEA_Obj( oxName='LOX', fuelName='LH2', make_debug_prints=True)
Isp = C.get_Isp(Pc=100.0, MR=1.0, eps=40.0)
print( Isp )
