### ISSUE TITLE
A question on licensing / SUA

### ISSUE THREAD

**Issue by eliasboegel** [sonofeft/RocketCEA#19]
Hi,
When I came across this package, a question arose for me: I also have an original copy of CEA, however the user agreement for the copy states that the user may not distribute the software publicly, but only internally and one must make sure to only distribute to persons that meet export control restrictions. This here is a public repository, so I am wondering how this project sticks to the NASA software user agreement. Was this consideration made?

Thanks!

**Comment by sonofeft** [comment]
Yes. Permission was requested and given by NASA in May of 2018 to publish a GPL-3 open source project

**Comment by eliasboegel** [comment]
Great, thanks a lot for answering!

**Comment by a093130** [comment]
C. Taylor,

Actually, this question will keep coming up (had it myself, was afraid to ask), unless you include a copy of the NASA email or permission letter either in your LICENSE.txt file or comment the NASA code within RocketCEA/NASA_CEA_Fortran.  I suggest you do one of those before closing Issue #19.

I also see that Glenn has approved CEA for O.S. and Foreign Release (https://software.nasa.gov/software/LEW-17687-1).  You might also include such a statement to head off the inevitable ITAR/CCL concerns.

Cheers!

Colin Helms
+1-310-750-8902

**Comment by sonofeft** [comment]
I have contacted NASA again regarding this open source version of CEA. 

They said that while CEA was openly downloadable in the past, it has since been changed to "U.S. and Foreign Release".
    
They also said, however, that they are hesitant to pull this project down.

I'm told that NASA will review the situation and let me know.

I will post their final determination and, of course, comply with their requirements.
