### ISSUE TITLE
No Isp output when using HYD## at high expansion ratio

### ISSUE THREAD

**Issue by rogerscoryo** [sonofeft/RocketCEA#48]
When using the example code located here https://rocketcea.readthedocs.io/en/latest/hydrazine_mono.html to plot Isp, Cstar, and Tchamb for varying amounts of ammonia dissociation the Isp output is zero. The example uses an expansion ratio of 20:1. When the expansion ratio is increased to 130:1 Isp is stuck at zero starting at roughly 50% ammonia dissociation. Why does RocketCEA not output Isp for high ammonia dissociation percent at high expansion ratios?

**Comment by sonofeft** [comment]
Likely the problem is that at high area ratios the exit temperature gets extremely cold and multi-phase flow becomes a problem that the  NASA CEA code can not handle. The code below runs on my setup and gives and Isp at 50% dissociation and 130:1 nozzle. You might want to pay attention to the exit temperature and species mole fractions to diagnose the execution boundary.

```
from rocketcea.cea_obj import CEA_Obj

hyd =  CEA_Obj( propName='HYD50')

kwargs = {'Pc': 200.0, 'eps':130}  
output = hyd.get_full_cea_output(**kwargs)
print( output )

```
